apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbd-snapclass
snapshotter: csi-rbd
parameters:
  pool: replicapool
  monitors: 10.0.0.67:6789,10.0.0.67:3300
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system