apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: rbd-pvc-snapshot
spec:
  snapshotClassName: csi-rbd-snapclass
  source:
    name: rbd-pvc
    kind: PersistentVolumeClaim