apiVersion: storage.tke.cloud.tencent.com/v1
kind: CSI
metadata:
  name: hostpath
spec:
  driverName: csi-hostpath
  driverTemplate:
    template:
      spec:
        hostNetwork: true
        containers:
        - name: hostpath
          image: quay.io/k8scsi/hostpathplugin:canary
          args:
          - "--v=5"
          - "--endpoint=$(CSI_ENDPOINT)"
          - "--nodeid=$(KUBE_NODE_NAME)"
          - "--drivername=csi-hostpath"
          env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /csi-data-dir
            name: csi-data-dir
        volumes:
        - name: csi-data-dir
          hostPath:
            # 'path' is where PV data is persisted on host.
            # using /tmp is also possible while the PVs will not available after plugin container recreation or host reboot
            path: /tmp/hostpath
            type: DirectoryOrCreate
  node:
    nodeRegistrar:
      image: quay.io/k8scsi/csi-node-driver-registrar:canary
    livenessProbe:
      image: quay.io/k8scsi/livenessprobe:canary
  controller:
    replicas: 1
    provisioner:
      image: quay.io/k8scsi/csi-provisioner:canary
      resources:
        limits:
          "cpu": 100m
          "memory": 100Mi
    attacher:
      image: quay.io/k8scsi/csi-attacher:canary
      resources:
        limits:
          "cpu": 100m
          "memory": 100Mi
    snapshotter:
      image: quay.io/k8scsi/csi-snapshotter:canary
      resources:
        limits:
          "cpu": 100m
          "memory": 100Mi
    clusterRegistrar:
      image: quay.io/k8scsi/csi-cluster-driver-registrar:canary
    livenessProbe:
      image: quay.io/k8scsi/livenessprobe:canary
  storageClasses:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: csi-hostpath-sc
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
