apiVersion: storage.tke.cloud.tencent.com/v1
kind: CSI
metadata:
  name: cephfs
  namespace: kube-system
spec:
  driverName: csi-cephfs
  driverTemplate:
    template:
      spec:
        hostNetwork: true
        # to use e.g. Rook orchestrated cluster, and mons' FQDN is
        # resolved through k8s service, set dns policy to cluster first
        dnsPolicy: ClusterFirstWithHostNet
        containers:
        - name: csi-cephfs
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/cephcsi/cephfsplugin:v0.3.0
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=5"
            - "--drivername=csi-cephfs"
            - "--metadatastorage=k8s_configmap"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: mount-cache-dir
              mountPath: /mount-cache-dir
            - name: host-sys
              mountPath: /sys
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: host-dev
              mountPath: /dev
        volumes:
        - name: mount-cache-dir
          emptyDir: {}
        - name: host-sys
          hostPath:
            path: /sys
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: host-dev
          hostPath:
            path: /dev
  node:
    nodeRegistrar:
      image: quay.io/k8scsi/driver-registrar:v0.3.0
    livenessProbe:
      image: quay.io/k8scsi/livenessprobe:v0.4.1
      parameters:
        storage.tke.cloud.tencent.com/liveness-probe-port: "9819"
  controller:
    replicas: 1
    provisioner:
      image: quay.io/k8scsi/csi-provisioner:v0.4.2
      resources:
        limits:
          "cpu": 100m
          "memory": 100Mi
    attacher:
      image: quay.io/k8scsi/csi-attacher:v0.4.2
      resources:
        limits:
          "cpu": 100m
          "memory": 100Mi
    livenessProbe:
      image: quay.io/k8scsi/livenessprobe:v0.4.1
      parameters:
        storage.tke.cloud.tencent.com/liveness-probe-port: "9818"
  secrets:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: csi-cephfs-secret
      namespace: kube-system
    data:
      adminID: YWRtaW4=
      adminKey: QVFCZHI4SmNDZEk3SnhBQWhHL0N4akxFdW05RUI2bUMrRGEza1E9PQ==
  storageClasses:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
       name: csi-cephfs
    provisioner: csi-cephfs
    parameters:
        provisionVolume: "true"
        monitors: 10.0.0.27:6789,10.0.0.27:3300
        pool: myfs-data0
        csiProvisionerSecretName: csi-cephfs-secret
        csiProvisionerSecretNamespace: kube-system
        csiNodeStageSecretName: csi-cephfs-secret
        csiNodeStageSecretNamespace: kube-system
        adminid: admin
        userid: admin
    reclaimPolicy: Delete