kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-operator
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-operator
    spec:
      serviceAccount: csi-operator
      containers:
        - name: csi-operator
          image: csi-operator:latest
          args:
            - "--leader-election=true"
            - "--kubelet-root-dir=/var/lib/kubelet"
            - "--logtostderr=true"
            - "--v=5"
          imagePullPolicy: "IfNotPresent"
